# Generated by Django 3.2.9 on 2021-11-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_bookstore', '0006_auto_20211123_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_bookstore.cart', verbose_name='Корзина'),
        ),
    ]
