# Generated by Django 3.2.9 on 2021-12-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_bookstore', '0010_auto_20211130_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurevalidator',
            name='category',
        ),
        migrations.RemoveField(
            model_name='featurevalidator',
            name='feature_key',
        ),
        migrations.RemoveField(
            model_name='productfeatures',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='productfeatures',
            name='product',
        ),
        migrations.DeleteModel(
            name='CategoryFeature',
        ),
        migrations.DeleteModel(
            name='FeatureValidator',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
    ]
